{
    market :  [
        {
        '$': {code: 'Ftb_23', name: 'Handicap', id: '27136512'},
        choice: [[Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object]]
        },
        {
            '$': {code: 'Ftb_Tgl', name: 'Total Goals', id: '27136517'},
            choice: [[Object], [Object], [Object]]
        },
        {
            '$': {code: 'Ftb_Htr', name: 'Half-Time Result', id: '27136526'},
            choice: [[Object], [Object], [Object]]
        },
        {
            '$': {code: 'Ftb_Csc', name: 'Correct Score', id: '27136544'},
            choice: [[Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object]]
        },
        {
            '$': {
                code: 'Ftb_Hcs',
                name: 'Half-Time Correct Score',
                id: '27136553'
            },
            choice: [[Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object]]
        },
        {
            '$': {code: 'Ftb_10', name: 'Over/Under', id: '27136556'},
            choice: [[Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object]]
        },
        {
            '$': {code: 'Ftb_Dbc', name: 'Double Chance', id: '27136559'},
            choice: [[Object], [Object], [Object]]
        },
        {
            '$': {code: 'Ftb_Mr3', name: 'Match Result', id: '27136562'},
            choice: [[Object], [Object], [Object]]
        },
        {
            '$': {
                code: 'Ftb_Htf',
                name: 'Half-Time / Full-Time',
                id: '27136568'
            },
            choice: [[Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object]]
        },
        {
            '$': {code: 'Ftb_Fts', name: 'First Team To Score', id: '27136579'},
            choice: [[Object], [Object], [Object]]
        }]
}